name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-name: 'Latest rolling build'
        asset-name: 'hmlog-linux'
        file: 'build/hmlog'
    
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
    - name: Clean build directory
      run: rm -rf build
    - name: Build for windows
      run: make CXX=x86_64-w64-mingw32-g++
    - name: release for windows
      uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-name: 'Latest rolling build'
        asset-name: 'hmlog-windows.exe'
        file: 'build/hmlog.exe'
